create table if not exists public.zestquest_26_score_log (
  id bigint generated by default as identity primary key,
  team_name text not null,
  score integer not null,
  added_by text not null,
  is_admin boolean not null default false,
  remarks text,
  created_at timestamptz not null default now()
);

alter table public.zestquest_26_score_log enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'zestquest_26_score_log'
      and policyname = 'Enable read access for all users'
  ) then
    create policy "Enable read access for all users"
    on public.zestquest_26_score_log
    for select
    to anon
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'zestquest_26_score_log'
      and policyname = 'Enable score logging for all users'
  ) then
    create policy "Enable score logging for all users"
    on public.zestquest_26_score_log
    for insert
    to anon
    with check (true);
  end if;
end
$$;

create index if not exists zestquest_26_score_log_team_name_idx
on public.zestquest_26_score_log(team_name);

create index if not exists zestquest_26_score_log_created_at_idx
on public.zestquest_26_score_log(created_at desc);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'zestquest_26_score_log'
    )
  then
    alter publication supabase_realtime add table public.zestquest_26_score_log;
  end if;
end
$$;

create table if not exists public.zestquest_26_scoreboard_state (
  id smallint primary key default 1 check (id = 1),
  is_frozen boolean not null default false,
  frozen_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.zestquest_26_scoreboard_state (id, is_frozen, frozen_at)
values (1, false, null)
on conflict (id) do nothing;

alter table public.zestquest_26_scoreboard_state enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'zestquest_26_scoreboard_state'
      and policyname = 'Enable scoreboard state read access for all users'
  ) then
    create policy "Enable scoreboard state read access for all users"
    on public.zestquest_26_scoreboard_state
    for select
    to anon
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'zestquest_26_scoreboard_state'
      and policyname = 'Enable scoreboard state updates for all users'
  ) then
    create policy "Enable scoreboard state updates for all users"
    on public.zestquest_26_scoreboard_state
    for update
    to anon
    using (id = 1)
    with check (id = 1);
  end if;
end
$$;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'zestquest_26_scoreboard_state'
    )
  then
    alter publication supabase_realtime add table public.zestquest_26_scoreboard_state;
  end if;
end
$$;
